# ! ONLY FOR DEV; NOT FOR PRODUCTION

services:
  revproxy:
    image: nginx:1.25
    restart: unless-stopped
    networks:
      - skynet
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - api
  frontend:
    image: taskscheduler/webclient:1.0
    build:
      context: .
      dockerfile: ./docker/node/dev.Dockerfile
    networks:
      - skynet
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - .env:/usr/src/app/.env
    depends_on:
      - api
  api:
    image: taskscheduler/api:1.0
    build:
      context: .
      dockerfile: ./docker/go/dev.Dockerfile
    networks:
      - skynet
    volumes:
      - ./server:/usr/src/app
      - .env:/usr/src/app/.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    networks:
      - skynet
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
  redis:
    image: redis:7
    networks:
      - skynet
    ports:
      - "6379:6379"

networks:
  skynet:
    driver: bridge

volumes:
  data:
    driver: local
  node_modules:
