server {
    listen 80 default_server;
    root /var/www/html/public;

	index index.html index.htm;

	server_name _;

	charset utf-8;

	location /api {
	    proxy_set_header X-Csrf 1;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_pass http://api-prod:3000/api;
	}

	location / {
	    try_files $uri $uri/ /index.html;
	}

	location ~ /\.ht {
	   deny all;
	}
}
