import { sql } from 'drizzle-orm';
import { integer, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Column helpers shared by every table, so the conventions in spec §5.1 and
 * §5.4 are stated once rather than repeated per table.
 */

/** UUID v7 (spec §5.1): time-ordered, which aids index locality and gives
 *  deterministic tie-breaks in the scheduler (§6.3). Generated by Postgres 18's
 *  native `uuidv7()` so ids are ordered by the database's clock, not a client's. */
export const primaryKeyColumn = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`);

/** Optimistic locking (spec §5.4). Maintained by the `touch_row()` trigger —
 *  never assigned by application code; commands only *check* it. */
export const versionColumn = () => integer('version').notNull().default(1);

export const createdAtColumn = () =>
  timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow();

/** Bumped by the `touch_row()` trigger alongside `version`. */
export const updatedAtColumn = () =>
  timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow();
