import { sql } from 'drizzle-orm';
import { integer, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Column helpers shared by every table, so the conventions in spec §5.1 and
 * §5.4 are stated once rather than repeated per table.
 */

/** UUID v7 (spec §5.1): time-ordered, which aids index locality and gives
 *  deterministic tie-breaks in the scheduler (§6.3). Generated by Postgres 18's
 *  native `uuidv7()` so ids are ordered by the database's clock, not a client's. */
export const primaryKeyColumn = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`);

/** Optimistic locking (spec §5.4). Maintained by the `touch_row()` trigger —
 *  never assigned by application code; commands only *check* it. */
export const versionColumn = () => integer('version').notNull().default(1);

export const createdAtColumn = () =>
  timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow();

/** Bumped by the `touch_row()` trigger alongside `version`. */
export const updatedAtColumn = () =>
  timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow();

/**
 * The same two columns, presented to JavaScript as `Date` rather than as an
 * ISO string.
 *
 * Used only by the tables Better Auth reads and writes (spec §10.1): `users`,
 * `tenants`, `memberships`, and the four it owns outright. Its adapter hands
 * the driver `Date` objects and converts what comes back into `Date` either
 * way, so a string-mode column would be handed a value it cannot serialise.
 *
 * The stored type is identical — `timestamp with time zone`, UTC, per §5.1.
 * What differs is the representation this side of the driver, and it differs
 * for exactly the tables a library owns. Everything the app itself reads
 * timestamps out of stays on strings, which is what the scheduler's
 * `toInstant` expects.
 */
export const createdAtDateColumn = () =>
  timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow();

export const updatedAtDateColumn = () =>
  timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow();
